# Change these first
owner: FreeCode911 # Your GitHub organization or username, where this repository lives
repo: TryStatus # The name of this repository

sites:
  - name: LykCloud
    url: https://lykcloud.com
  - name: Dashboard
    url: https://manage.lykcloud.com/
  - name: Panel
    url: http://control.lykcloud.com/
  - name: Minolink
    url: https://minolink.us.kg/
  - name: PicGenV - API
    url: https://text-to-image.legendyt4k.me/
 # - name: IPv6 test
  #  url: forwardemail.net
  #  port: 80
  #  check: "tcp-ping"
 #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.lykcloud.com
  # baseUrl: /your-repo-name
  logoUrl: https://lykfile.me/cn/CD0322-Untitled_design-removebg-preview.png
  name: LykCloud 24/7
  introTitle: "** Welcome!** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Welcome to the LykCloud Status Page! Here, you can check the current status of our services, monitor system performance, and stay updated with any ongoing maintenance or incidents.
  navbar:
    - title: Status
      href: /
    - title: Discord
      href: https://discord.gg/JzDArmmmy7
    - title: YouTube
      href: https://youtube.com/@legendyt4k
    - title: Free Hosting
      href: https://lykcloud.com
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
